config/routes.rb
Rails.application.routes.draw do
  root "companies#index"
  resources :job_boards, only: [:index]
  resources :companies, only: [:index, :show, :new, :create]
end

app/models/company.rb
require 'open-uri'
require 'nokogiri'

class Company < ActiveRecord::Base
  validates :link, presence: true
  validates :name, presence: true

  def self.nokogiri_parse(company)
    Nokogiri::HTML(open("#{company.link}"))
  end

  def self.css_attr
     {
        'ruby news' => '#jobs-list a',
        'ruby insider' => '.title .jam_link',
        'rails job' => '.jobitem a',
        'ruby on rails jobs' => '#jobs-table a',
        'top ruby jobs' => '#jobs a',
        'engineer jobs' => '.jobtitle',
        'careers stackoverflow' => 'h3 .job-link',
        'monster' => '.fnt11 span',
        'indeed' => '.jobtitle a',
        'ruby on rails' => '#content li a',
        'we work remotely' => '#category-2 li a',
        'flex jobs' => '#joblist a'

     }
  end

  def self.companies(array)

    data = {}
    array.each do |company|
     data[company.name] = nokogiri_parse(company).css(Company.css_attr[company.name])
    end
    data
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
    @time = Time.now.strftime("%B  %d")
  end

  def show
    @companies = Company.companies(Company.all)
    @name = Company.find(params[:id]).name
    @company = @companies[@name]
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to root_path
    else
      render new_company_path
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.erb
<div class='row'>
  <h1> Last Updated <%= @time %></h1>
  <ul>
  <% @companies.each do |company| %>
    <li><h3><%= link_to company.name, company_path(company.id), class: 'job' %></h3></li>
  <% end %>
  </ul>
</div>

app/views/companies/new.html.erb
<div class="row">
  <div class="small-8 large-centered columns">
    <h1>Add new company</h1>
  </div>

  <%= form_for @company do |f| %>
    <div class="small-8 large-centered columns">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="small-8 large-centered columns">
      <%= f.label :link %>
      <%= f.text_field :link %>
    </div>

    <div class="small-8 large-centered columns">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/companies/show.html.erb
<h1><%= @name %> - <%= link_to 'go back', root_path %></h1>

<ul>
  <% @company.each do |job| %>
    <% if job.attributes['href'].nil? %>
      <li><%= link_to job.children.text, job.attributes.values[0].value %></li>
    <% else %>
      <li><%= link_to job.children.text, job.attributes["href"].value %></li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class='row'>
      <div class='large-10 small-12 columns'>
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav id='access' class="top-bar" data-topbar>
  <ul class="nav-bar">
    <li class="name">
      <h1><a href="/">Job Board</a></h1>
    </li>
  </ul>
</nav>